HOFF-632 Update-ARE-to-HOF-v20.4.0
UKHomeOffice/AppealRightsExhausted pull request #142
Opened 2024-03-05 11:14 UTC by TemitopeAyokuHO

## What?
[HOFF-632 ](https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-632).- changing Queen's crown to King's crown logo
 
## Why?
The Gov.uk crown logo changed
 
## How?
npm install hof@20.4.0
 
## Testing?
Tested locally
 
## Screenshots (optional)
 
![Screenshot 2024-02-29 at 16 23 35](https://github.com/UKHomeOffice/AppealRightsExhausted/assets/138882912/519943b0-8271-47bd-b22d-fe7fe341b6d2)

2024-03-05 23:27 UTC, Rhodine-orleans-lindsay requested changes

2024-03-05 23:27 UTC, Rhodine-orleans-lindsay commented on package-lock.json
Please delete this file - we use yarn.lock so don't need package-lock.json(it was probably created by running ```npm install``` instead of ```yarn```

2024-03-06 09:12 UTC, TemitopeAyokuHO commented on package-lock.json
applied changes

2024-03-06 12:34 UTC, Rhodine-orleans-lindsay requested changes

2024-03-06 12:34 UTC, Rhodine-orleans-lindsay commented on apps/are_form/data/exclusion_days.json
>  }
there is a new line error here

2024-03-06 13:51 UTC, TemitopeAyokuHO commented on apps/are_form/data/exclusion_days.json
>  }
added

2024-03-06 14:14 UTC, Rhodine-orleans-lindsay approved these changes
lgtm

2024-03-12 14:28 UTC, merged